//==============================================================================
//        This file was generated by the NX Block Styler
//        Created by: chenjie
//              Version: NX 10
//              Date: 02-20-2017  (Format: mm-dd-yyyy)
//              Time: 23:20
//
//==============================================================================

#ifndef PCF_TOOL_H_INCLUDED
#define PCF_TOOL_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------

#include <iostream>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include "ufd_route_pcf_generation.hpp"

#include <windows.h>
#undef CreateDialog


//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace NXOpen;
using namespace NXOpen::BlockStyler;
using namespace std;

class DllExport pcf_tool
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    pcf_tool();
    ~pcf_tool();
    int Show();
    void RegisterWithMenu();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the pcf_tool.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
	void Splite(string input_str, char* symbol, vector<string>& output_str);
	void TcharToChar(const TCHAR * tchar, char * _char);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    NXOpen::BlockStyler::Button* button01;// Block type: Button

	Part *workPart;
	Part *displayPart;
    
};
#endif //PCF_TOOL_H_INCLUDED
